export const initialPlayers = [
  {
    name: "陆梓鑫",
    number: 3,
    category: "后卫",
    age: 23,
    position: "LB",
    role: "工兵型执行者",
    foot: "左脚",
    height: "173cm",
    weight: "65kg",
    ability: 74,
    potential: 82,
    rarity: "银卡稀有",
    cardType: "工兵型执行者",
    tags: ["跑动", "执行力", "左路稳定"],
    attributes: {
      速度: 74,
      射门: 52,
      传球: 69,
      盘带: 72,
      防守: 73,
      身体: 70,
    },
    strengths: ["跑动覆盖积极", "纪律性好", "左脚边路资源", "执行力强"],
    suggestions: [
      "前插时可以更果断，帮助左路形成进攻宽度。",
      "传球选择上可以适当增加向前比例。",
      "继续保持防守稳定性，同时提升传中质量。",
    ],
    summary: "左路稳定型球员，适合承担防守、补位和边路衔接任务。",
    matches: [],
  },
  {
    name: "戴天麒",
    number: 17,
    category: "中场",
    age: 17,
    position: "CDM / RB",
    role: "防守屏障",
    foot: "右脚",
    height: "未知",
    weight: "未知",
    ability: 80,
    potential: 86,
    rarity: "金卡稀有",
    cardType: "扫荡型屏障",
    tags: ["扫荡者", "拦截", "高覆盖", "对抗强"],
    attributes: {
      速度: 72,
      射门: 48,
      传球: 65,
      盘带: 63,
      防守: 82,
      身体: 84,
    },
    strengths: ["覆盖面积大", "对抗能力强", "防守意识良好", "工作投入高"],
    suggestions: [
      "面对快速反击时，建议更注意纵向位置保护。",
      "出球时可以更耐心选择。",
      "在领先时保持专注。",
    ],
    summary: "负责中场防守保护，拦截对手进攻，为球队提供稳定屏障。",
    matches: [],
  },
  {
    name: "吴易纬",
    number: 11,
    category: "前场",
    age: 20,
    position: "LW / RW / CAM",
    role: "前场多面手",
    foot: "右脚",
    height: "未知",
    weight: "未知",
    ability: 78,
    potential: 80,
    rarity: "金卡普通",
    cardType: "前场推进点",
    tags: ["突破", "创造", "多位置适配"],
    attributes: {
      速度: 82,
      射门: 70,
      传球: 74,
      盘带: 82,
      防守: 50,
      身体: 68,
    },
    strengths: ["前场位置适应性强", "持球推进能力好", "具备边路突破能力"],
    suggestions: [
      "可以增加无球跑动频率。",
      "突破后选择更果断一些。",
      "在前腰位置时增加一脚出球比例。",
    ],
    summary: "前场多面手，可承担 LW、RW、CAM 多个角色。",
    matches: [],
  },
  {
    name: "贾玉乐",
    number: 9,
    category: "前场",
    age: 20,
    position: "LW / ST",
    role: "前场冲击点 / 支点球员",
    foot: "右脚",
    height: "未知",
    weight: "未知",
    ability: 72,
    potential: 74,
    rarity: "银卡普通",
    cardType: "前场支点",
    tags: ["身体优势", "前场支点", "边路冲击"],
    attributes: {
      速度: 68,
      射门: 70,
      传球: 58,
      盘带: 66,
      防守: 42,
      身体: 82,
    },
    strengths: ["身体优势明显", "能牵制防守球员", "具备边路冲击能力"],
    suggestions: [
      "可以多利用身体优势保护球权。",
      "从左路启动时提前观察中路队友。",
      "背身拿球后减少停顿，提高处理效率。",
    ],
    summary: "前场力量型球员，适合承担支点、牵制和边路冲击任务。",
    matches: [],
  },
];
